# Generated by Django 3.2.7 on 2021-09-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh', models.IntegerField()),
                ('milk', models.IntegerField()),
                ('grocery', models.IntegerField()),
                ('frozem', models.IntegerField()),
                ('detergents_paper', models.IntegerField()),
                ('delicassen', models.IntegerField()),
                ('channel_1', models.IntegerField(default=0)),
                ('channel_2', models.IntegerField(default=0)),
                ('region_1', models.IntegerField(default=0)),
                ('region_2', models.IntegerField(default=0)),
                ('region_3', models.IntegerField(default=0)),
            ],
        ),
    ]
