# Generated by Django 3.2.7 on 2021-09-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='channel_1',
            new_name='Channel_1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='channel_2',
            new_name='Channel_2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='delicassen',
            new_name='Delicassen',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='detergents_paper',
            new_name='Detergents_Paper',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fresh',
            new_name='Fresh',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='frozem',
            new_name='Frozen',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='grocery',
            new_name='Grocery',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='milk',
            new_name='Milk',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='region_1',
            new_name='Region_1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='region_2',
            new_name='Region_2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='region_3',
            new_name='Region_3',
        ),
    ]
